---
deployment:
  tasks:
    - export DEPLOYPATH=/home/agifiqsq/applications/mriet.conntog.com/
    - /bin/rm -rf $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp -R app.py $DEPLOYPATH
    - /bin/cp -R requirements.txt $DEPLOYPATH
    - /bin/cp -R passenger_wsgi.py $DEPLOYPATH
